spring:
  datasource:
    url: jdbc:mariadb://binter.synology.me:3307/barfdog?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: britishinter
    password: Britain001!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

# 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/Users/verin/jyh/upload

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
